# Generated by Django 2.2.4 on 2019-08-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_dois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_dois_de', to='rest_api.Pessoa')),
                ('pessoa_um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_um_de', to='rest_api.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filhos', models.ManyToManyField(to='rest_api.Pessoa')),
                ('uniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Uniao')),
            ],
        ),
    ]
